hoistPattern:
  - '*'
hoistedDependencies:
  '@cesium/engine@22.1.0':
    '@cesium/engine': private
  '@cesium/wasm-splats@0.1.0-alpha.2':
    '@cesium/wasm-splats': private
  '@cesium/widgets@14.1.0':
    '@cesium/widgets': private
  '@nodelib/fs.scandir@2.1.5':
    '@nodelib/fs.scandir': private
  '@nodelib/fs.stat@2.0.5':
    '@nodelib/fs.stat': private
  '@nodelib/fs.walk@1.2.8':
    '@nodelib/fs.walk': private
  '@oxc-project/runtime@0.97.0':
    '@oxc-project/runtime': private
  '@oxc-project/types@0.97.0':
    '@oxc-project/types': private
  '@protobufjs/aspromise@1.1.2':
    '@protobufjs/aspromise': private
  '@protobufjs/base64@1.1.2':
    '@protobufjs/base64': private
  '@protobufjs/codegen@2.0.4':
    '@protobufjs/codegen': private
  '@protobufjs/eventemitter@1.1.0':
    '@protobufjs/eventemitter': private
  '@protobufjs/fetch@1.1.0':
    '@protobufjs/fetch': private
  '@protobufjs/float@1.0.2':
    '@protobufjs/float': private
  '@protobufjs/inquire@1.1.0':
    '@protobufjs/inquire': private
  '@protobufjs/path@1.1.2':
    '@protobufjs/path': private
  '@protobufjs/pool@1.1.0':
    '@protobufjs/pool': private
  '@protobufjs/utf8@1.1.0':
    '@protobufjs/utf8': private
  '@rolldown/binding-darwin-arm64@1.0.0-beta.50':
    '@rolldown/binding-darwin-arm64': private
  '@rolldown/pluginutils@1.0.0-beta.50':
    '@rolldown/pluginutils': private
  '@sindresorhus/merge-streams@4.0.0':
    '@sindresorhus/merge-streams': private
  '@spz-loader/core@0.3.0':
    '@spz-loader/core': private
  '@tweenjs/tween.js@25.0.0':
    '@tweenjs/tween.js': private
  '@types/node@25.0.3':
    '@types/node': private
  '@types/trusted-types@2.0.7':
    '@types/trusted-types': private
  '@zip.js/zip.js@2.8.11':
    '@zip.js/zip.js': private
  autolinker@4.1.5:
    autolinker: private
  bitmap-sdf@1.0.4:
    bitmap-sdf: private
  braces@3.0.3:
    braces: private
  commander@2.20.3:
    commander: private
  copy-file@11.1.0:
    copy-file: private
  cpy@12.1.0:
    cpy: private
  detect-libc@2.1.2:
    detect-libc: private
  dompurify@3.3.1:
    dompurify: private
  draco3d@1.5.7:
    draco3d: private
  earcut@3.0.2:
    earcut: private
  fast-glob@3.3.3:
    fast-glob: private
  fastq@1.20.1:
    fastq: private
  fdir@6.5.0(picomatch@4.0.3):
    fdir: private
  fill-range@7.1.1:
    fill-range: private
  fsevents@2.3.3:
    fsevents: private
  glob-parent@5.1.2:
    glob-parent: private
  globby@15.0.0:
    globby: private
  graceful-fs@4.2.11:
    graceful-fs: private
  grapheme-splitter@1.0.4:
    grapheme-splitter: private
  ignore@7.0.5:
    ignore: private
  is-extglob@2.1.1:
    is-extglob: private
  is-glob@4.0.3:
    is-glob: private
  is-number@7.0.0:
    is-number: private
  jsep@1.4.0:
    jsep: private
  junk@4.0.1:
    junk: private
  kdbush@4.0.2:
    kdbush: private
  ktx-parse@1.1.0:
    ktx-parse: private
  lerc@2.0.0:
    lerc: private
  lightningcss-darwin-arm64@1.30.2:
    lightningcss-darwin-arm64: private
  lightningcss@1.30.2:
    lightningcss: private
  long@5.3.2:
    long: private
  meow@13.2.0:
    meow: private
  merge2@1.4.1:
    merge2: private
  mersenne-twister@1.1.0:
    mersenne-twister: private
  meshoptimizer@0.25.0:
    meshoptimizer: private
  micromatch@4.0.8:
    micromatch: private
  nanoid@3.3.11:
    nanoid: private
  nosleep.js@0.12.0:
    nosleep.js: private
  p-event@6.0.1:
    p-event: private
  p-filter@4.1.0:
    p-filter: private
  p-map@7.0.4:
    p-map: private
  p-timeout@6.1.4:
    p-timeout: private
  pako@2.1.0:
    pako: private
  path-type@6.0.0:
    path-type: private
  picocolors@1.1.1:
    picocolors: private
  picomatch@4.0.3:
    picomatch: private
  postcss@8.5.6:
    postcss: private
  protobufjs@7.5.4:
    protobufjs: private
  queue-microtask@1.2.3:
    queue-microtask: private
  quickselect@3.0.0:
    quickselect: private
  rbush@4.0.1:
    rbush: private
  reusify@1.1.0:
    reusify: private
  rolldown@1.0.0-beta.50:
    rolldown: private
  run-parallel@1.2.0:
    run-parallel: private
  slash@5.1.0:
    slash: private
  source-map-js@1.2.1:
    source-map-js: private
  tinyglobby@0.2.15:
    tinyglobby: private
  to-regex-range@5.0.1:
    to-regex-range: private
  topojson-client@3.1.0:
    topojson-client: private
  tslib@2.8.1:
    tslib: private
  undici-types@7.16.0:
    undici-types: private
  unicorn-magic@0.3.0:
    unicorn-magic: private
  urijs@1.19.11:
    urijs: private
included:
  dependencies: true
  devDependencies: true
  optionalDependencies: true
injectedDeps: {}
layoutVersion: 5
nodeLinker: isolated
packageManager: pnpm@10.26.1
pendingBuilds: []
prunedAt: Sat, 03 Jan 2026 20:19:50 GMT
publicHoistPattern: []
registries:
  '@jsr': https://npm.jsr.io/
  default: https://registry.npmjs.org/
skipped:
  - '@emnapi/core@1.8.0'
  - '@emnapi/runtime@1.8.0'
  - '@emnapi/wasi-threads@1.1.0'
  - '@napi-rs/wasm-runtime@1.1.1'
  - '@rolldown/binding-android-arm64@1.0.0-beta.50'
  - '@rolldown/binding-darwin-x64@1.0.0-beta.50'
  - '@rolldown/binding-freebsd-x64@1.0.0-beta.50'
  - '@rolldown/binding-linux-arm-gnueabihf@1.0.0-beta.50'
  - '@rolldown/binding-linux-arm64-gnu@1.0.0-beta.50'
  - '@rolldown/binding-linux-arm64-musl@1.0.0-beta.50'
  - '@rolldown/binding-linux-x64-gnu@1.0.0-beta.50'
  - '@rolldown/binding-linux-x64-musl@1.0.0-beta.50'
  - '@rolldown/binding-openharmony-arm64@1.0.0-beta.50'
  - '@rolldown/binding-wasm32-wasi@1.0.0-beta.50'
  - '@rolldown/binding-win32-arm64-msvc@1.0.0-beta.50'
  - '@rolldown/binding-win32-ia32-msvc@1.0.0-beta.50'
  - '@rolldown/binding-win32-x64-msvc@1.0.0-beta.50'
  - '@tybys/wasm-util@0.10.1'
  - lightningcss-android-arm64@1.30.2
  - lightningcss-darwin-x64@1.30.2
  - lightningcss-freebsd-x64@1.30.2
  - lightningcss-linux-arm-gnueabihf@1.30.2
  - lightningcss-linux-arm64-gnu@1.30.2
  - lightningcss-linux-arm64-musl@1.30.2
  - lightningcss-linux-x64-gnu@1.30.2
  - lightningcss-linux-x64-musl@1.30.2
  - lightningcss-win32-arm64-msvc@1.30.2
  - lightningcss-win32-x64-msvc@1.30.2
storeDir: /Users/capynq/Library/pnpm/store/v10
virtualStoreDir: .pnpm
virtualStoreDirMaxLength: 120
